//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_course_sort
    {
        public int c_id { get; set; }
        public System.Guid c_sort_id { get; set; }
        public int parent_id { get; set; }
        public string class_name { get; set; }
        public string c_img { get; set; }
        public string describe { get; set; }
        public int sort { get; set; }
        public System.DateTime c_db_create_date { get; set; }
        public int c_db_create_id { get; set; }
        public System.DateTime c_db_last_update_date { get; set; }
        public int c_db_last_update_id { get; set; }
        public int c_db_status { get; set; }
    }
}
