//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_log_sms
    {
        public int c_sms_id { get; set; }
        public string c_sms_type { get; set; }
        public string c_sms_userid { get; set; }
        public string c_sms_msg { get; set; }
        public string c_sms_phone { get; set; }
        public string c_sms_return_code { get; set; }
        public string c_sms_code { get; set; }
        public string c_sms_func { get; set; }
        public string c_sms_ip { get; set; }
    }
}
