//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_member_login
    {
        public int c_id { get; set; }
        public System.Guid c_member_id { get; set; }
        public string c_login_date { get; set; }
        public string c_login_status { get; set; }
        public string c_login_ip { get; set; }
        public string c_login_src { get; set; }
    }
}
