//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_payment
    {
        public int c_id { get; set; }
        public System.Guid c_payment_id { get; set; }
        public int c_payment_way { get; set; }
        public decimal c_payment_amount { get; set; }
        public string c_transaction_number { get; set; }
        public string c_serial_number { get; set; }
        public System.Guid c_member_id { get; set; }
        public System.DateTime c_payment_date { get; set; }
        public string c_order_number { get; set; }
        public System.DateTime c_db_create_date { get; set; }
        public int c_db_create_id { get; set; }
        public System.DateTime c_db_last_update_date { get; set; }
        public int c_db_last_update_id { get; set; }
        public int c_db_status { get; set; }
    }
}
